# Generated by Django 2.2 on 2019-11-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='details',
            new_name='detail',
        ),
    ]
