# Generated by Django 2.2 on 2020-03-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200311_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(verbose_name='课程详情'),
        ),
    ]
